name: resume_builder
description: Make your free resume now!


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  url_launcher: ^6.0.18
  cupertino_icons: ^1.0.2
  path_provider: ^2.0.5
  responsive_framework: ^1.0.0
  pdf: ^3.6.5
  flutter_riverpod: ^1.0.3
  get: ^4.3.8
  freezed_annotation: ^2.2.0
  freezed: ^2.3.2
  build_runner: ^2.0.4
  intl: ^0.18.0
  pdf_render: ^1.0.19
  printing: ^5.3.0
  universal_html: ^2.0.8
  
  google_fonts: ^4.0.3
  json_serializable: ^6.6.1
  adaptive_theme: ^3.2.0
  uuid: ^3.0.4
  cloud_firestore: ^4.5.2
  firebase_auth: ^4.4.2
  firebase_core: ^2.10.0
  firebase_database: ^10.1.1
  flutterfire_ui: ^0.4.3+20
  url_strategy: ^0.2.0
  localstorage: ^4.0.1+2
  shared_preferences: ^2.1.0
  card_swiper: ^2.0.4
  font_awesome_flutter: ^10.4.0
  flutter_custom_clippers: ^2.1.0
  lottie: ^2.3.2
  line_icons: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true
  assets:
    - assets/lottie/
    - assets/images/